// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/articles.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListRequest struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9464f3c4be8a2f7f, []int{0}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ListRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type ListReply struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt            string   `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListReply) Reset()         { *m = ListReply{} }
func (m *ListReply) String() string { return proto.CompactTextString(m) }
func (*ListReply) ProtoMessage()    {}
func (*ListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9464f3c4be8a2f7f, []int{1}
}

func (m *ListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReply.Unmarshal(m, b)
}
func (m *ListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReply.Marshal(b, m, deterministic)
}
func (m *ListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReply.Merge(m, src)
}
func (m *ListReply) XXX_Size() int {
	return xxx_messageInfo_ListReply.Size(m)
}
func (m *ListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListReply proto.InternalMessageInfo

func (m *ListReply) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ListReply) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ListReply) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ListReply) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type DetailRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailRequest) Reset()         { *m = DetailRequest{} }
func (m *DetailRequest) String() string { return proto.CompactTextString(m) }
func (*DetailRequest) ProtoMessage()    {}
func (*DetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9464f3c4be8a2f7f, []int{2}
}

func (m *DetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailRequest.Unmarshal(m, b)
}
func (m *DetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailRequest.Marshal(b, m, deterministic)
}
func (m *DetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailRequest.Merge(m, src)
}
func (m *DetailRequest) XXX_Size() int {
	return xxx_messageInfo_DetailRequest.Size(m)
}
func (m *DetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DetailRequest proto.InternalMessageInfo

func (m *DetailRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DetailReply struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	CreatedAt            string   `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailReply) Reset()         { *m = DetailReply{} }
func (m *DetailReply) String() string { return proto.CompactTextString(m) }
func (*DetailReply) ProtoMessage()    {}
func (*DetailReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9464f3c4be8a2f7f, []int{3}
}

func (m *DetailReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailReply.Unmarshal(m, b)
}
func (m *DetailReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailReply.Marshal(b, m, deterministic)
}
func (m *DetailReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailReply.Merge(m, src)
}
func (m *DetailReply) XXX_Size() int {
	return xxx_messageInfo_DetailReply.Size(m)
}
func (m *DetailReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailReply.DiscardUnknown(m)
}

var xxx_messageInfo_DetailReply proto.InternalMessageInfo

func (m *DetailReply) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DetailReply) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *DetailReply) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *DetailReply) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*ListRequest)(nil), "proto.ListRequest")
	proto.RegisterType((*ListReply)(nil), "proto.ListReply")
	proto.RegisterType((*DetailRequest)(nil), "proto.DetailRequest")
	proto.RegisterType((*DetailReply)(nil), "proto.DetailReply")
}

func init() { proto.RegisterFile("proto/articles.proto", fileDescriptor_9464f3c4be8a2f7f) }

var fileDescriptor_9464f3c4be8a2f7f = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x6d, 0x9a, 0x56, 0x32, 0x41, 0x91, 0x21, 0x87, 0x50, 0x10, 0xcb, 0x9e, 0x3c, 0x45,
	0xfc, 0xf3, 0x05, 0x0a, 0x1e, 0x3d, 0xe5, 0x0b, 0x48, 0x9a, 0xdd, 0xc2, 0xc0, 0xea, 0xc4, 0xcd,
	0x78, 0xc8, 0xb7, 0x97, 0xce, 0x6e, 0xa1, 0xed, 0xc5, 0x9e, 0x32, 0xf3, 0x7b, 0x6f, 0xc8, 0xdb,
	0x07, 0xd5, 0x10, 0x58, 0xf8, 0xa9, 0x0b, 0x42, 0xbd, 0x77, 0x63, 0xa3, 0x2b, 0x2e, 0xf4, 0x63,
	0x9e, 0xa1, 0xfc, 0xa0, 0x51, 0x5a, 0xf7, 0xf3, 0xeb, 0x46, 0x41, 0x84, 0x7c, 0x17, 0xf8, 0xab,
	0x9e, 0xad, 0x67, 0x8f, 0x45, 0xab, 0x33, 0xde, 0x42, 0x26, 0x5c, 0x67, 0x4a, 0x32, 0x61, 0x13,
	0xa0, 0x88, 0x27, 0x83, 0x9f, 0xf6, 0x22, 0x59, 0xb5, 0xcf, 0xdb, 0x8c, 0x2c, 0x56, 0xb0, 0x10,
	0x12, 0xef, 0x92, 0x3f, 0x2e, 0xb8, 0x86, 0xd2, 0xba, 0xb1, 0x0f, 0x34, 0x08, 0xf1, 0x77, 0x3d,
	0x57, 0xed, 0x18, 0xe1, 0x3d, 0x40, 0x1f, 0x5c, 0x27, 0xce, 0x7e, 0x76, 0x52, 0xe7, 0x6a, 0x28,
	0x12, 0xd9, 0x88, 0x79, 0x80, 0x9b, 0x77, 0x27, 0x1d, 0xf9, 0x43, 0xd0, 0xb3, 0xff, 0x9a, 0x1d,
	0x94, 0x07, 0xc3, 0xe5, 0xb1, 0x10, 0xf2, 0x2d, 0xdb, 0x29, 0xe5, 0xd1, 0xf9, 0x9f, 0x20, 0x2f,
	0x0c, 0xd7, 0x9b, 0x58, 0x24, 0x36, 0x90, 0xef, 0x7b, 0x40, 0x8c, 0x8d, 0x36, 0x47, 0x3d, 0xae,
	0xee, 0x4e, 0xd8, 0xe0, 0x27, 0x73, 0x85, 0x6f, 0xb0, 0x8c, 0x11, 0xb1, 0x4a, 0xea, 0xc9, 0x93,
	0x56, 0x78, 0x46, 0xf5, 0x6a, 0xbb, 0x54, 0xf8, 0xfa, 0x17, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x90,
	0x1a, 0x5a, 0xc6, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ArticleClient is the client API for Article service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ArticleClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error)
	Detail(ctx context.Context, in *DetailRequest, opts ...grpc.CallOption) (*DetailReply, error)
}

type articleClient struct {
	cc *grpc.ClientConn
}

func NewArticleClient(cc *grpc.ClientConn) ArticleClient {
	return &articleClient{cc}
}

func (c *articleClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error) {
	out := new(ListReply)
	err := c.cc.Invoke(ctx, "/proto.Article/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) Detail(ctx context.Context, in *DetailRequest, opts ...grpc.CallOption) (*DetailReply, error) {
	out := new(DetailReply)
	err := c.cc.Invoke(ctx, "/proto.Article/Detail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleServer is the server API for Article service.
type ArticleServer interface {
	List(context.Context, *ListRequest) (*ListReply, error)
	Detail(context.Context, *DetailRequest) (*DetailReply, error)
}

// UnimplementedArticleServer can be embedded to have forward compatible implementations.
type UnimplementedArticleServer struct {
}

func (*UnimplementedArticleServer) List(ctx context.Context, req *ListRequest) (*ListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedArticleServer) Detail(ctx context.Context, req *DetailRequest) (*DetailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Detail not implemented")
}

func RegisterArticleServer(s *grpc.Server, srv ArticleServer) {
	s.RegisterService(&_Article_serviceDesc, srv)
}

func _Article_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Article/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_Detail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).Detail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Article/Detail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).Detail(ctx, req.(*DetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Article_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Article",
	HandlerType: (*ArticleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Article_List_Handler,
		},
		{
			MethodName: "Detail",
			Handler:    _Article_Detail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/articles.proto",
}
